#! /usr/bin/python

'''
@file demo_py_momentumopt
@package momentumopt
@author Brahayam Ponton (brahayam.ponton@tuebingen.mpg.de)
@license License BSD-3-Clause
@copyright Copyright (c) 2019, New York University and Max Planck Gesellschaft.
@date 2019-10-08
'''

import sys
from momentumopt.kino_dyn_planner import main

if __name__ == "__main__":
    main(sys.argv[1:])
